apiVersion: v1
kind: Service
metadata:
  name: elayday
spec:
  ports:
    - port: 8080
      targetPort: rpc
      protocol: TCP
  selector:
    app: elayday
    role: main
---
apiVersion: v1
kind: Service
metadata:
  name: elayday-reflector
spec:
  ports:
    - port: 24601
      targetPort: 24601
      protocol: UDP
  selector:
    app: elayday
    role: reflector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elayday
spec:
  selector:
    matchLabels:
      app: elayday
      role: main
  replicas: 1
  template:
    metadata:
      labels:
        app: elayday
        role: main
    spec:
      containers:
        - name: elayday
          image: elayday
          imagePullPolicy: Always
          args:
            [
              "server",
              "--bind",
              "0.0.0.0:24601",
              "--destination",
              "elayday-reflector:24601",
              "--bind-grpc",
              "0.0.0.0:24602",
            ]
          readinessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc_health_probe"
                - "-addr=:24602"
                - "-service=elayday.Elayday"
            initialDelaySeconds: 5
          livenessProbe:
            exec:
              command:
                - "/usr/local/bin/grpc_health_probe"
                - "-addr=:24602"
                - "-service=elayday.Elayday"
            initialDelaySeconds: 10
          ports:
            - containerPort: 24601
              name: inbox
            - containerPort: 24602
              name: rpc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elayday-reflector
spec:
  selector:
    matchLabels:
      app: elayday
      role: reflector
  replicas: 1
  template:
    metadata:
      labels:
        app: elayday
        role: reflector
    spec:
      containers:
        - name: elayday
          image: elayday
          imagePullPolicy: Always
          args: ["reflector", "--bind", "0.0.0.0:24601", "--delay", "1"]
          ports:
            - containerPort: 24601
              name: inbox
